server:
  port: 8080

logging:
  level:
    com:
      bank:
        accounts: DEBUG

spring:
  application:
    name: "accounts"
  profiles:
    active: "prod"
#    not using mysql to avoid running an extra container as we have limited local ram capacity
#  datasource:
#    url: jdbc:mysql://localhost:3306/accountsdb
#    username: root
#    password: root
#  jpa:
#    show-sql: true
#  sql:
#    init:
#      mode: always
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    datasource-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: "optional:configserver:http://localhost:8071/"

#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

#actuator config
management:
  endpoints:
    web:
      exposure:
#        include: "refresh"
        # * means we've exposed all our actuator endpoints
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "accounts"
    description: "Account microservice of Bank Application"
    version: 1.0.0