spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to Bank accounts related local PROD APIs "
  contactDetails:
    name: "Glen Maxwell - Developer"
    email: "glen@bank.com"
  onCallSupport:
    - 912323564563
    - 982124368644